services:
  q1_filter_amount_0:
    build:
      context: ./src/
      dockerfile: business/common_workers/filter/Dockerfile
    container_name: q1_filter_amount_0
    depends_on:
      rabbitmq: &id001
        condition: service_healthy
      gateway:
        condition: service_started
    volumes:
    - ./data/q1_filter_amount_0:/data
    environment:
    - FILTER_AMOUNT=3
    - QUERY_NUMBER=1
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=q1_filter_amount
    - OUTPUT_QUEUES=results_queue
    - MAX_AMOUNT=50
    - ADD_QUERY_ID=True
    - BATCH_SIZE=10000
    - CONTAINER_NAME=q1_filter_amount_0
    - WATCHDOG_COUNT=3
  q1_filter_amount_1:
    build:
      context: ./src/
      dockerfile: business/common_workers/filter/Dockerfile
    container_name: q1_filter_amount_1
    depends_on:
      rabbitmq: *id001
      gateway:
        condition: service_started
    volumes:
    - ./data/q1_filter_amount_1:/data
    environment:
    - FILTER_AMOUNT=3
    - QUERY_NUMBER=1
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=q1_filter_amount
    - OUTPUT_QUEUES=results_queue
    - MAX_AMOUNT=50
    - ADD_QUERY_ID=True
    - BATCH_SIZE=10000
    - CONTAINER_NAME=q1_filter_amount_1
    - WATCHDOG_COUNT=3
  q1_filter_amount_2:
    build:
      context: ./src/
      dockerfile: business/common_workers/filter/Dockerfile
    container_name: q1_filter_amount_2
    depends_on:
      rabbitmq: *id001
      gateway:
        condition: service_started
    volumes:
    - ./data/q1_filter_amount_2:/data
    environment:
    - FILTER_AMOUNT=3
    - QUERY_NUMBER=1
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=q1_filter_amount
    - OUTPUT_QUEUES=results_queue
    - MAX_AMOUNT=50
    - ADD_QUERY_ID=True
    - BATCH_SIZE=10000
    - CONTAINER_NAME=q1_filter_amount_2
    - WATCHDOG_COUNT=3
  filter_usd_0:
    build:
      context: ./src/
      dockerfile: business/common_workers/filter/Dockerfile
    container_name: filter_usd_0
    depends_on:
      rabbitmq: *id001
      q1_filter_amount_0: &id002
        condition: service_started
      q1_filter_amount_1: &id003
        condition: service_started
      q1_filter_amount_2: &id004
        condition: service_started
    volumes:
    - ./data/filter_usd_0:/data
    environment:
    - FILTER_AMOUNT=3
    - QUERY_NUMBER=1
    - INPUT_EXCHANGE_NAME=input_gateway_exchange
    - INPUT_ROUTING_KEYS=filter_usd
    - MOM_HOST=rabbitmq
    - OUTPUT_QUEUES=q1_filter_amount
    - USD_ONLY=True
    - BATCH_SIZE=10000
    - CONTAINER_NAME=filter_usd_0
    - WATCHDOG_COUNT=3
  filter_usd_1:
    build:
      context: ./src/
      dockerfile: business/common_workers/filter/Dockerfile
    container_name: filter_usd_1
    depends_on:
      rabbitmq: *id001
      q1_filter_amount_0: *id002
      q1_filter_amount_1: *id003
      q1_filter_amount_2: *id004
    volumes:
    - ./data/filter_usd_1:/data
    environment:
    - FILTER_AMOUNT=3
    - QUERY_NUMBER=1
    - INPUT_EXCHANGE_NAME=input_gateway_exchange
    - INPUT_ROUTING_KEYS=filter_usd
    - MOM_HOST=rabbitmq
    - OUTPUT_QUEUES=q1_filter_amount
    - USD_ONLY=True
    - BATCH_SIZE=10000
    - CONTAINER_NAME=filter_usd_1
    - WATCHDOG_COUNT=3
  filter_usd_2:
    build:
      context: ./src/
      dockerfile: business/common_workers/filter/Dockerfile
    container_name: filter_usd_2
    depends_on:
      rabbitmq: *id001
      q1_filter_amount_0: *id002
      q1_filter_amount_1: *id003
      q1_filter_amount_2: *id004
    volumes:
    - ./data/filter_usd_2:/data
    environment:
    - FILTER_AMOUNT=3
    - QUERY_NUMBER=1
    - INPUT_EXCHANGE_NAME=input_gateway_exchange
    - INPUT_ROUTING_KEYS=filter_usd
    - MOM_HOST=rabbitmq
    - OUTPUT_QUEUES=q1_filter_amount
    - USD_ONLY=True
    - BATCH_SIZE=10000
    - CONTAINER_NAME=filter_usd_2
    - WATCHDOG_COUNT=3
  client0:
    container_name: client
    build:
      context: ./src
      dockerfile: client/Dockerfile
    depends_on:
      filter_usd_0:
        condition: service_started
      filter_usd_1:
        condition: service_started
      filter_usd_2:
        condition: service_started
    environment:
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
    - INPUT_FILE=/datasets/HI-Medium_Trans.csv
    - OUTPUT_FILE=/output/client0/output.csv
    - BATCH_SIZE=10000
    volumes:
    - ./datasets:/datasets
    - ./output:/output
  gateway:
    build:
      context: ./src/
      dockerfile: gateway/Dockerfile
    container_name: gateway
    depends_on:
      rabbitmq: *id001
    environment:
    - INPUT_EXCHANGE_NAME=input_gateway_exchange
    - INPUT_ROUTING_KEYS=filter_usd
    - MOM_HOST=rabbitmq
    - OUTPUT_QUEUE=results_queue
    - NUM_EXPECTED_EOFS=1
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
    - BATCH_SIZE=1000
    - CONTAINER_NAME=gateway
    - WATCHDOG_COUNT=3
  rabbitmq:
    build:
      context: ./src/
      dockerfile: rabbitmq/Dockerfile
    container_name: rabbitmq
    volumes:
    - ./data/rabbitmq:/var/lib/rabbitmq
    environment:
    - RABBITMQ_LOG_LEVELS=error
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
    - 5672:5672
    - 15672:15672
  watchdog_0:
    build:
      context: ./src/
      dockerfile: watchdog/Dockerfile
    container_name: watchdog_0
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - MOM_HOST=rabbitmq
    - HEARTBEAT_TIMEOUT=10
    - WATCHDOG_ID=0
    - WATCHDOG_COUNT=3
    - WATCHDOG_HEARTBEAT_INTERVAL=3
    - WATCHDOG_TIMEOUT=10
    - REVIVE_INTERVAL=5
    - WORKER_EXCHANGE=heartbeat_exchange
    - PEER_EXCHANGE=watchdog_exchange
    depends_on:
      rabbitmq: *id001
  watchdog_1:
    build:
      context: ./src/
      dockerfile: watchdog/Dockerfile
    container_name: watchdog_1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - MOM_HOST=rabbitmq
    - HEARTBEAT_TIMEOUT=10
    - WATCHDOG_ID=1
    - WATCHDOG_COUNT=3
    - WATCHDOG_HEARTBEAT_INTERVAL=3
    - WATCHDOG_TIMEOUT=10
    - REVIVE_INTERVAL=5
    - WORKER_EXCHANGE=heartbeat_exchange
    - PEER_EXCHANGE=watchdog_exchange
    depends_on:
      rabbitmq: *id001
  watchdog_2:
    build:
      context: ./src/
      dockerfile: watchdog/Dockerfile
    container_name: watchdog_2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - MOM_HOST=rabbitmq
    - HEARTBEAT_TIMEOUT=10
    - WATCHDOG_ID=2
    - WATCHDOG_COUNT=3
    - WATCHDOG_HEARTBEAT_INTERVAL=3
    - WATCHDOG_TIMEOUT=10
    - REVIVE_INTERVAL=5
    - WORKER_EXCHANGE=heartbeat_exchange
    - PEER_EXCHANGE=watchdog_exchange
    depends_on:
      rabbitmq: *id001
  chaos_monkey:
    build:
      context: ./src/
      dockerfile: chaos_monkey/Dockerfile
    container_name: chaos_monkey
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - KILL_INTERVAL=60
    - EXCLUDE_CONTAINERS=rabbitmq,chaos_monkey,gateway,client
    depends_on:
      rabbitmq: *id001
