services:
  client0:
    container_name: client
    build:
      context: ./src
      dockerfile: client/Dockerfile
    depends_on:
      filter_q5_amount_0:
        condition: service_started
      filter_q5_amount_1:
        condition: service_started
    environment:
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
    - INPUT_FILE=/datasets/HI-Medium_Trans.csv
    - OUTPUT_FILE=/output/client0/output.csv
    - BATCH_SIZE=10000
    volumes:
    - ./datasets:/datasets
    - ./output:/output
  gateway:
    build:
      context: ./src/
      dockerfile: gateway/Dockerfile
    container_name: gateway
    depends_on:
      rabbitmq: &id001
        condition: service_healthy
    environment:
    - INPUT_QUEUE=filter_q5_fmt_queue
    - MOM_HOST=rabbitmq
    - OUTPUT_QUEUE=results_queue
    - NUM_EXPECTED_EOFS=1
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
    - BATCH_SIZE=10000
  filter_q5_fmt_0:
    build:
      context: ./src/
      dockerfile: business/common_workers/filter/Dockerfile
    container_name: filter_q5_fmt_0
    depends_on:
      rabbitmq: *id001
      gateway:
        condition: service_started
    environment:
    - QUERY_NUMBER=5
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=filter_q5_fmt_queue
    - OUTPUT_QUEUES=converter_queue
    - FILTER_AMOUNT=7
    - GE_DATE=2022-09-01
    - LE_DATE=2022-09-05
    - PAY_FMTS=Wire,ACH
    - BATCH_SIZE=10000
  filter_q5_fmt_1:
    build:
      context: ./src/
      dockerfile: business/common_workers/filter/Dockerfile
    container_name: filter_q5_fmt_1
    depends_on:
      rabbitmq: *id001
      gateway:
        condition: service_started
    environment:
    - QUERY_NUMBER=5
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=filter_q5_fmt_queue
    - OUTPUT_QUEUES=converter_queue
    - FILTER_AMOUNT=7
    - GE_DATE=2022-09-01
    - LE_DATE=2022-09-05
    - PAY_FMTS=Wire,ACH
    - BATCH_SIZE=10000
  filter_q5_fmt_2:
    build:
      context: ./src/
      dockerfile: business/common_workers/filter/Dockerfile
    container_name: filter_q5_fmt_2
    depends_on:
      rabbitmq: *id001
      gateway:
        condition: service_started
    environment:
    - QUERY_NUMBER=5
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=filter_q5_fmt_queue
    - OUTPUT_QUEUES=converter_queue
    - FILTER_AMOUNT=7
    - GE_DATE=2022-09-01
    - LE_DATE=2022-09-05
    - PAY_FMTS=Wire,ACH
    - BATCH_SIZE=10000
  filter_q5_fmt_3:
    build:
      context: ./src/
      dockerfile: business/common_workers/filter/Dockerfile
    container_name: filter_q5_fmt_3
    depends_on:
      rabbitmq: *id001
      gateway:
        condition: service_started
    environment:
    - QUERY_NUMBER=5
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=filter_q5_fmt_queue
    - OUTPUT_QUEUES=converter_queue
    - FILTER_AMOUNT=7
    - GE_DATE=2022-09-01
    - LE_DATE=2022-09-05
    - PAY_FMTS=Wire,ACH
    - BATCH_SIZE=10000
  filter_q5_fmt_4:
    build:
      context: ./src/
      dockerfile: business/common_workers/filter/Dockerfile
    container_name: filter_q5_fmt_4
    depends_on:
      rabbitmq: *id001
      gateway:
        condition: service_started
    environment:
    - QUERY_NUMBER=5
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=filter_q5_fmt_queue
    - OUTPUT_QUEUES=converter_queue
    - FILTER_AMOUNT=7
    - GE_DATE=2022-09-01
    - LE_DATE=2022-09-05
    - PAY_FMTS=Wire,ACH
    - BATCH_SIZE=10000
  filter_q5_fmt_5:
    build:
      context: ./src/
      dockerfile: business/common_workers/filter/Dockerfile
    container_name: filter_q5_fmt_5
    depends_on:
      rabbitmq: *id001
      gateway:
        condition: service_started
    environment:
    - QUERY_NUMBER=5
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=filter_q5_fmt_queue
    - OUTPUT_QUEUES=converter_queue
    - FILTER_AMOUNT=7
    - GE_DATE=2022-09-01
    - LE_DATE=2022-09-05
    - PAY_FMTS=Wire,ACH
    - BATCH_SIZE=10000
  filter_q5_fmt_6:
    build:
      context: ./src/
      dockerfile: business/common_workers/filter/Dockerfile
    container_name: filter_q5_fmt_6
    depends_on:
      rabbitmq: *id001
      gateway:
        condition: service_started
    environment:
    - QUERY_NUMBER=5
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=filter_q5_fmt_queue
    - OUTPUT_QUEUES=converter_queue
    - FILTER_AMOUNT=7
    - GE_DATE=2022-09-01
    - LE_DATE=2022-09-05
    - PAY_FMTS=Wire,ACH
    - BATCH_SIZE=10000
  converter_0:
    build:
      context: ./src/
      dockerfile: business/common_workers/converter/Dockerfile
      network: host
    container_name: converter_0
    depends_on:
      rabbitmq: *id001
      filter_q5_fmt_0: &id002
        condition: service_started
      filter_q5_fmt_1: &id003
        condition: service_started
      filter_q5_fmt_2: &id004
        condition: service_started
      filter_q5_fmt_3: &id005
        condition: service_started
      filter_q5_fmt_4: &id006
        condition: service_started
      filter_q5_fmt_5: &id007
        condition: service_started
      filter_q5_fmt_6: &id008
        condition: service_started
    environment:
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=converter_queue
    - OUTPUT_QUEUE=filter_q5_amount_queue
    - CONVERTER_AMOUNT=3
    - FRANKFURTER_BASE=https://api.frankfurter.dev/v2
    - BATCH_SIZE=10000
  converter_1:
    build:
      context: ./src/
      dockerfile: business/common_workers/converter/Dockerfile
      network: host
    container_name: converter_1
    depends_on:
      rabbitmq: *id001
      filter_q5_fmt_0: *id002
      filter_q5_fmt_1: *id003
      filter_q5_fmt_2: *id004
      filter_q5_fmt_3: *id005
      filter_q5_fmt_4: *id006
      filter_q5_fmt_5: *id007
      filter_q5_fmt_6: *id008
    environment:
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=converter_queue
    - OUTPUT_QUEUE=filter_q5_amount_queue
    - CONVERTER_AMOUNT=3
    - FRANKFURTER_BASE=https://api.frankfurter.dev/v2
    - BATCH_SIZE=10000
  converter_2:
    build:
      context: ./src/
      dockerfile: business/common_workers/converter/Dockerfile
      network: host
    container_name: converter_2
    depends_on:
      rabbitmq: *id001
      filter_q5_fmt_0: *id002
      filter_q5_fmt_1: *id003
      filter_q5_fmt_2: *id004
      filter_q5_fmt_3: *id005
      filter_q5_fmt_4: *id006
      filter_q5_fmt_5: *id007
      filter_q5_fmt_6: *id008
    environment:
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=converter_queue
    - OUTPUT_QUEUE=filter_q5_amount_queue
    - CONVERTER_AMOUNT=3
    - FRANKFURTER_BASE=https://api.frankfurter.dev/v2
    - BATCH_SIZE=10000
  filter_q5_amount_0:
    build:
      context: ./src/
      dockerfile: business/common_workers/filter/Dockerfile
    container_name: filter_q5_amount_0
    depends_on:
      rabbitmq: *id001
      converter_0: &id009
        condition: service_started
      converter_1: &id010
        condition: service_started
      converter_2: &id011
        condition: service_started
    environment:
    - QUERY_NUMBER=5
    - ADD_QUERY_ID=True
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=filter_q5_amount_queue
    - OUTPUT_QUEUES=results_queue
    - FILTER_AMOUNT=2
    - MAX_AMOUNT=1.0
    - BATCH_SIZE=10000
  filter_q5_amount_1:
    build:
      context: ./src/
      dockerfile: business/common_workers/filter/Dockerfile
    container_name: filter_q5_amount_1
    depends_on:
      rabbitmq: *id001
      converter_0: *id009
      converter_1: *id010
      converter_2: *id011
    environment:
    - QUERY_NUMBER=5
    - ADD_QUERY_ID=True
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=filter_q5_amount_queue
    - OUTPUT_QUEUES=results_queue
    - FILTER_AMOUNT=2
    - MAX_AMOUNT=1.0
    - BATCH_SIZE=10000
  rabbitmq:
    build:
      context: ./src/
      dockerfile: rabbitmq/Dockerfile
    container_name: rabbitmq
    environment:
    - RABBITMQ_LOG_LEVELS=error
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
    - 5672:5672
    - 15672:15672
